#!/bin/sh /etc/rc.common

START=20
STOP=90

SERVICE_DAEMONIZE=1
SERVICE_WRITE_PID=1

init_switch() {
	. /lib/network/switch.sh
	include /lib/network
	setup_switch
	
}

start() {
	stop
	[ -e /proc/sys/kernel/core_pattern ] && {
		ulimit -c unlimited
		echo '/tmp/%e.%p.%s.%t.core' > /proc/sys/kernel/core_pattern
	}
	service_start /sbin/netifd

	init_switch

	#sleep 5
	
	#del wifi by xiaowei 2016-2-24
	#/sbin/wifi down
	#/sbin/wifi up
}

restart() {
	ifdown -a
	sleep 1
	start
}

shutdown() {
	ifdown -a
	stop
}

stop() {
	service_stop /sbin/netifd
}

reload() {
	init_switch
	ubus call network reload
	
	#del wifi by xiaowei 2016-2-24
	#/sbin/wifi down
	#/sbin/wifi up
}
