build:
	@echo "BUILD	wifidog"
	cd ./src && make build && cd -
	
install:
	@echo "INSTALL 	wifidog"
	cd ./src && make install && cd -

clean:
	@echo "CLEAN 	wifidog"
	cd ./src && make clean && cd -
	rm -rf ipk*
