# This makefile snippet is generated by the mrouted configure script.

# Initial definitions ...
# -D_GNU_SOURCE Use GNU extensions, where possible
# -D_BSD_SOURCE Use functions derived from 4.3 BSD Unix rather than POSIX.1
DEFS          = -D_BSD_SOURCE -D_GNU_SOURCE
# EXTRA_OBJS  = For locally provided objects missing on some platforms, e.g., strlcpy.o
# EXTRA_LIBS  = For platform specific libraries, e.g., -lutil

# Linux specific settings ...
INCLUDES     = $(INCLUDE_DIR)
DEFS        += -DIOCTL_OK_ON_RAW_SOCKET
EXTRA_OBJS   = strlcpy.o pidfile.o strtonum.o
EXTRA_LIBS   =

# Enabled features ...
DEFS         += -DRSRR
RSRR_OBJS     = rsrr.o
INCLUDES     += -I
