#!/bin/sh
# Copyright (C) 2006 OpenWrt.org



#default set luci.custom.strip to 1
if [ -f /usr/lib/lua/luci/custom.lua ];then
	uci set luci.sauth=internal
	uci set luci.sauth.sessionpath=/tmp/luci-sessions
	uci set luci.sauth.sessiontime=3600
	uci set luci.custom=internal
	uci set luci.custom.strip=1
	uci commit
fi


run_scripts() {
	for i in /etc/rc.d/$1*; do
		[ -x $i ] && $i $2 2>&1
	done | $LOGGER
}

system_config() {
	config_get_bool foreground $1 foreground 0
}

LOGGER="cat"
[ -x /usr/bin/logger ] && LOGGER="logger -s -p 6 -t sysinit"

. /lib/functions.sh

config_load system
config_foreach system_config system

if [ "$1" = "S" -a "$foreground" != "1" ]; then
	run_scripts "$1" "$2" &
else
	run_scripts "$1" "$2"
fi
