# ------------------------------------------------------------------------------
# Copyright (C) 2008 Robert Ernst <robert.ernst@aon.at>
#
# This file may be distributed and/or modified under the terms of the
# GNU General Public License version 2 as published by the Free Software
# Foundation and appearing in the file LICENSE.GPL included in the
# packaging of this file.
#
# This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
# WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
# 
# See COPYING for GPL licensing information.
#



# ------------------------------------------------------------------------------
# Build instructions
#
# For cross-compilation, define CC, e.g. CC=arm-linux-gcc
# For debugging code, add -DDEBUG -g to OFLAGS
# For optimizing code, add -O2 to OFLAGS
# For compiling for IPv4 only, change CFLAGS from -D__IPV6__ to -D__IPV4__
# For compiling for FreeBSD, change CFLAGS from -D__LINUX__ to -D__FREEBSD__
# For compiling the demo extension, add -D__DEMO__ to CFLAGS
# To compile the programm, simply call 'make'
#

obj-app = snmpagentd
obj-dep	= mib.o globals.o utils.o linux.o freebsd.o \
	  interface_app.o \
	  interface_wireless.o \
	  interface_route.o \
	  my_snmp_ioctl.o \
          snmp_nms.o \
          my_snmp_alarm.o\
          my_snmp_util.o \
          my_snmp_handle.o \
          my_snmp_protocol.o \
          my_snmp_config.o \
          my_snmp_data.o \
          my_snmp_info.o \
          my_snmp_init.o \
          my_snmp_scalar_handler.o \
          my_snmp_table_handler.o \
          my_snmp_trap.o \
          mini_snmpd.o \
	  $(APP_COMMON)/nvram_flash.o
VERSION = 1.2b
VENDOR	= .1.3.6.1.4.1

OFLAGS	= -O2 -DDEBUG -DSYSLOG -g -static -pthread -lrt -DGBCOM_ADD -DBIGENDIAN -D__AP_BGSCAN__ -DMGSOFT
CFLAGS	= -I$(APP_INCLUDE) -I. -I$(KERNELPATH)/include -Wall -DVERSION="\"$(VERSION)\"" -DVENDOR="\"$(VENDOR)\"" \
	  $(OFLAGS) -D__TRAPS__ -D__LINUX__ -D__IPV4__
LDFLAGS	= $(OFLAGS)

DEST_PATH = $(BIN_PATH)/app/bin
DEST_NAME = $(obj-app)

include $(TOPDIR)/build/app.mk
