#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

SERVICE_MATCH_NAME=1
SERVICE_DAEMONIZE=1
START=98


start() {
	service_start /usr/sbin/multicast
}

stop() {
	service_stop /usr/sbin/multicast
}
